dist: xenial
language: python
python:
  - "3.7"

addons:
  sonarcloud:
    organization: "$SONAR_ORGANIZATION"
    token:
      secure: "$SONAR_TOKEN"

before_install:
  - pip install -U pip

install:
  - pip install -r requirements-mazelib.txt codecov
  - pip install -r requirements-dev.txt codecov

script:
  - pylint --extension-pkg-whitelist=spacy.symbols dork tests
  # https://github.com/PyCQA/pylint/issues/1524
  - flake8 dork tests
  - coverage erase
  - coverage run --branch --source=dork --omit=dork/__main__.py -m pytest
  - coverage report -m --fail-under=95
  
after_success:
  - coverage xml -i
  - codecov
  - sonar-scanner -Dsonar.projectKey=${SONAR_PROJECT_KEY} -Dsonar.organization=${SONAR_ORGANIZATION}
